import { get_order_calc, get_order_calc_export } from '../service/api';
import { downloadFile } from '../service/tools';
import { format } from 'date-fns';
import { loadingToggle } from '../blocks/loading';

window.orderOpen = async () => {
  loadingToggle();
  await moduleOpen('./src/html/orders.html').then(() => {
    ordersLoad();
    loadingToggle();
  });
};

window.orderExport = (id) => {
  get_order_calc_export(id)
    .then((response) => {
      downloadFile(response);
    })
    .catch((error) => {
      alert(`Ошибка скачивания файла с id: ${id}`);
      console.error(error);
    });
};

const testResult = {
  count: 68,
  results: [
    {
      calc_id: 1,
      calc_date: '2025-01-23',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 2,
      calc_date: '2025-01-23',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 1,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 23,
      calc_date: '2025-03-07',
      upper_bound_coeff: 4,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 3,
      calc_date: '2025-02-24',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 1,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'error',
      log: "Error in calc_safety_stock: Error dbt for final_order: Runtime Error\n  Could not find profile named 'dbt_forecast'",
    },
    {
      calc_id: 14,
      calc_date: '2025-03-07',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 4,
      calc_date: '2025-02-22',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 1,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 45,
      calc_date: '2025-03-13',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 43,
      calc_date: '2025-03-20',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'error',
      log: 'Error in safety stock calculation: Error in calc_safety_stock: Error dbt for forecast: None',
    },
    {
      calc_id: 5,
      calc_date: '2025-03-06',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 15,
      calc_date: '2025-03-07',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 90,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 24,
      calc_date: '2025-03-07',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 60,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 6,
      calc_date: '2025-03-10',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 31,
      calc_date: '2025-03-12',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 16,
      calc_date: '2025-03-14',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'error',
      log: 'Error in calc_safety_stock: Error dbt for final_order: None',
    },
    {
      calc_id: 40,
      calc_date: '2025-03-06',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 25,
      calc_date: '2025-03-10',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.95,
      z_coeff_under_forecast: 0.95,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 8,
      calc_date: '2025-03-04',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 17,
      calc_date: '2025-03-14',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 9,
      calc_date: '2025-03-05',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 10,
      calc_date: '2025-03-06',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'new',
      log: '',
    },
    {
      calc_id: 36,
      calc_date: '2025-03-28',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 32,
      calc_date: '2025-03-12',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 11,
      calc_date: '2025-03-07',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 26,
      calc_date: '2025-03-18',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.95,
      z_coeff_under_forecast: 0.95,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 12,
      calc_date: '2025-03-06',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 19,
      calc_date: '2025-03-07',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 90,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 50,
      calc_date: '2025-02-26',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 27,
      calc_date: '2025-03-10',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 20,
      calc_date: '2025-03-07',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 10,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 7,
      calc_date: '2025-03-03',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 13,
      calc_date: '2025-03-14',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 44,
      calc_date: '2025-03-20',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'error',
      log: 'Error in safety stock calculation: Error in calc_safety_stock: Error dbt for preprocess: None',
    },
    {
      calc_id: 21,
      calc_date: '2025-03-07',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.95,
      z_coeff_under_forecast: 0.95,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 33,
      calc_date: '2025-03-26',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 28,
      calc_date: '2025-03-10',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'error',
      log: 'Error in calc_safety_stock: Error dbt for final_order: None',
    },
    {
      calc_id: 22,
      calc_date: '2025-03-07',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 37,
      calc_date: '2025-03-13',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 29,
      calc_date: '2025-03-10',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'error',
      log: 'Error in calc_safety_stock: Error dbt for final_order: None',
    },
    {
      calc_id: 34,
      calc_date: '2025-03-28',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 30,
      calc_date: '2025-03-10',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: '',
    },
    {
      calc_id: 41,
      calc_date: '2025-03-28',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'error',
      log: 'Error in safety stock calculation: Error in calc_safety_stock: Error dbt for preprocess: None',
    },
    {
      calc_id: 39,
      calc_date: '2025-03-06',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'error',
      log: 'Error in safety stock calculation: Error in calc_safety_stock: Error dbt for preprocess: None',
    },
    {
      calc_id: 42,
      calc_date: '2025-03-28',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'error',
      log: 'Error in safety stock calculation: Error in calc_safety_stock: Error dbt for preprocess: None',
    },
    {
      calc_id: 35,
      calc_date: '2025-03-28',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 10,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 38,
      calc_date: '2025-03-20',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'error',
      log: 'Error in safety stock calculation: Error in calc_safety_stock: Error dbt for forecast: None',
    },
    {
      calc_id: 48,
      calc_date: '2025-03-13',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'error',
      log: 'Error in calc_safety_stock: Error dbt for final_order: None',
    },
    {
      calc_id: 46,
      calc_date: '2025-03-29',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 47,
      calc_date: '2025-03-29',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 51,
      calc_date: '2025-02-28',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 52,
      calc_date: '2025-03-21',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'new',
      log: null,
    },
    {
      calc_id: 49,
      calc_date: '2025-03-13',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'error',
      log: 'Error in safety stock calculation: Error in calc_safety_stock: Error dbt for preprocess: None',
    },
    {
      calc_id: 53,
      calc_date: '2025-03-21',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'new',
      log: null,
    },
    {
      calc_id: 54,
      calc_date: '2025-03-31',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 0.98,
      z_coeff_under_forecast: 0.98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'new',
      log: null,
    },
    {
      calc_id: 55,
      calc_date: '2025-03-21',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 56,
      calc_date: '2025-03-21',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 68,
      calc_date: '2025-03-21',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 57,
      calc_date: '2025-03-21',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 69,
      calc_date: '2025-03-21',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 59,
      calc_date: '2025-03-21',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'error',
      log: 'Error in safety stock calculation: Error in calc_safety_stock: Error dbt for preprocess: None',
    },
    {
      calc_id: 58,
      calc_date: '2025-03-21',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'error',
      log: 'Error in safety stock calculation: Error in calc_safety_stock: Error dbt for safety_stock: None',
    },
    {
      calc_id: 60,
      calc_date: '2025-03-21',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 61,
      calc_date: '2025-03-21',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'error',
      log: 'Error in safety stock calculation: Error in calc_safety_stock: Error dbt for forecast: None',
    },
    {
      calc_id: 62,
      calc_date: '2025-03-21',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'error',
      log: 'Error in safety stock calculation: Error in calc_safety_stock: Error dbt for preprocess: None',
    },
    {
      calc_id: 63,
      calc_date: '2025-03-21',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 64,
      calc_date: '2025-03-21',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
    {
      calc_id: 65,
      calc_date: '2025-03-21',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'error',
      log: 'Error in safety stock calculation: Error in calc_safety_stock: Error dbt for preprocess: None',
    },
    {
      calc_id: 66,
      calc_date: '2025-03-21',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'error',
      log: 'Error in safety stock calculation: Error in calc_safety_stock: Error dbt for preprocess: None',
    },
    {
      calc_id: 67,
      calc_date: '2025-03-21',
      upper_bound_coeff: 8,
      lower_bound_coeff: 4,
      trust_remains: 0,
      z_coeff_fluctuations: 98,
      z_coeff_under_forecast: 98,
      max_safety_stock_days: 30,
      max_safety_stock_percent: 50,
      delivery_frequency: 30,
      minimum_order_quantity_percent: 20,
      minimum_order_percent: 50,
      status: 'complete',
      log: null,
    },
  ],
  page_count: 1,
};

window.ordersLoad = (page = 1) => {
  loadingToggle();
  /*
  ordersRowDraw(testResult.results);
  loadingToggle();
  */
  return get_order_calc(page)
    .then((response) => {
      const { page_count, results } = response.data;
      ordersRowDraw(results);
      ordersUpdateMore({
        page_count: page_count,
        page: Number(page) + 1,
      });
    })
    .finally(() => {
      loadingToggle();
    });
};

function ordersRowDraw(list) {
  const table = document.getElementById('ordersTable').querySelector('tbody');
  let template = '';
  for (const el of list) {
    // <td align="center"><a href="./files/export_order_20250306_12.xlsx" class="btn btn-link p-0" data-id="${el['calc_id']}"><i class="fa fa-cloud-download-alt fa-2x"></i></a></td>
    template += `
      <tr>
        <td align="center"><button class="btn btn-link p-0" data-id="${el['calc_id']}" onclick="orderExport(${el['calc_id']});" ${el['status'] == 'error' || el['status'] == 'new' ? 'disabled' : ''}><i class="fa fa-cloud-download-alt fa-2x"></i></button></td>
        <td>${el['calc_id']}</td>
        <td>${format(new Date(el['calc_date']), 'dd.LL.yyy')}</td>
        <td>${el['status']}</td>
        <td>${el['upper_bound_coeff']}</td>
        <td>${el['lower_bound_coeff']}</td>
        <td>${el['trust_remains']}</td>
        <td>${el['z_coeff_fluctuations']}</td>
        <td>${el['z_coeff_under_forecast']}</td>
        <td>${el['max_safety_stock_days']}</td>
        <td>${el['max_safety_stock_percent']}</td>
        <td>${el['delivery_frequency']}</td>
        <td>${el['minimum_order_quantity_percent']}</td>
        <td>${el['minimum_order_percent']}</td>
        <td style="max-width: 220px;" title="${el['log'] || ''}">${el['log'] || ''}</td>
      </tr>
    `;
  }
  table.insertAdjacentHTML('beforeend', template);
}

function ordersUpdateMore(request) {
  const { page_count, page } = request;
  const btn = document.getElementById('ordersMore');
  btn.dataset.page = page;
  if (page_count < page) {
    btn.disabled = true;
  }
}
